### ISSUE TITLE
Update with change sets for multiple stacks fails unless all cause updates

### ISSUE THREAD

**Issue by henrist** [Sceptre/sceptre#723]
`update -c xxx` fails if there are multiple stacks resolved, and not all have updates (i.e. generates valid change sets). This is due to not all change sets statuses being READY, so it bails with `exit(1)`.

Party covered in #520, but this is a bug, not a broader improvement.

I've done some initial hacking on this issue and will try to push a PR soon.

**Comment by ngfgrant** [comment]
I _think_ https://github.com/cloudreach/sceptre/commit/987e22092a1efcfef8da0494e99a1b9ed083cd04 should fix this which is now in the 2.1.4

**Comment by henrist** [comment]
This is why it fails:

https://github.com/cloudreach/sceptre/blob/2.1.4/sceptre/cli/update.py#L60-L63

The code requires all items in the plan to have updates

**Comment by RobReus** [comment]
As far as I know, this is still an issue in `2.3.0`. Any idea when it will be fixed?

@henrist any chance of creating that pull request with the hacking you did on this issue? Might be able to help on solving this issue so it can be merged into upstream.

**Comment by ngfgrant** [comment]
This now might work when https://github.com/Sceptre/sceptre/commit/20b824a47c0b2330b29ef12e1c5643dddcb759e9 was merged to master (not formally released yet)

**Comment by henrist** [comment]
I'll devote some time during the weekend to check (both the changes mentioned and if needed push som partial changes in a PR).

**Comment by henrist** [comment]
The PR is out - see #917

**Comment by ngfgrant** [comment]
Thanks I’ll have a look soon I take it master doesn’t work?

**Comment by henrist** [comment]
> Thanks I’ll have a look soon I take it master doesn’t work?

Yep. The code i refered to in https://github.com/Sceptre/sceptre/issues/723#issuecomment-504398213 still caused the bailout.
