### ISSUE TITLE
Exception when sceptre scripts and sceptre installation is on different drives

### ISSUE THREAD

**Issue by adnanhb** [Sceptre/sceptre#863]
The following exception is thrown when the sceptre scripts and sceptre installation is on different drives:

`File "c:\python\3.7.0\lib\site-packages\sceptre\template.py", line 153, in _call_sceptre_handler
    relpath = os.path.relpath(self.path, os.getcwd()).split(os.path.sep)
  File "c:\python\3.7.0\lib\ntpath.py", line 564, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'c:', start on mount 'K:'`

**Comment by zaro0508** [comment]
same issue as #213 ?

**Comment by sree0213** [comment]
@adnanhb How this is resolved and don't see any related info in #213 
I have similar issue.

**Comment by ngfgrant** [comment]
It's not resolved it's closed as it is a duplicate of #213 which is open. 👍

**Comment by sree0213** [comment]
How to fix now then? is any alternative to get python pint to virtual env in I drive?

**Comment by ngfgrant** [comment]
@sree0213 sorry I don't understand what you are asking.

A sceptre project needs to be in the same drive, for now until we resolve #213

**Comment by sree0213** [comment]
@ngfgrant  Thanks.
